package user.dynamicTable;
// Generated May 20, 2023, 6:43:34 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TableDataId generated by hbm2java
 */
@Embeddable
public class TableDataId implements java.io.Serializable {

	private int tableId;
	private int rowNo;

	public TableDataId() {
	}

	public TableDataId(int tableId) {
		this.tableId = tableId;
		this.rowNo = 0;
	}

	@Column(name = "table_id", nullable = false)
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Column(name = "row_no", nullable = false)
	public int getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(int rowNo) {
		this.rowNo = rowNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TableDataId))
			return false;
		TableDataId castOther = (TableDataId) other;

		return (this.getTableId() == castOther.getTableId())
				&& (this.getRowNo() == castOther.getRowNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTableId();
		result = 37 * result + this.getRowNo();
		return result;
	}

}
