package user.dynamicTable;
// Generated May 20, 2023, 6:43:34 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TableData generated by hbm2java
 */
@Entity
@Table(name = "table_data")
public class TableData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TableDataId id;
	private String data;
	
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "tableId", column = @Column(name = "table_id", nullable = false)),
			@AttributeOverride(name = "rowNo", column = @Column(name = "row_no", nullable = false)) })
	public TableDataId getId() {
		return this.id;
	}

	public void setId(TableDataId id) {
		this.id = id;
	}
	
	public TableData(TableDataId id, String data) {
		super();
		this.id = id;
		this.data = data;
	}
	

	public TableData() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Column(name = "json_data")
	public String getData() {
		return data;
	}


	public void setData(String data) {
		this.data = data;
	}


	

	

}
