package user.inprocessChcks;
// Generated Jun 2, 2023, 2:52:26 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * StartupRecordData generated by hbm2java
 */
@Entity
@Table(name = "startup_record_data")
public class StartupRecordData implements java.io.Serializable {

	private StartupRecordDataId id;
	private String jsonData;

	public StartupRecordData() {
	}

	public StartupRecordData(StartupRecordDataId id) {
		this.id = id;
	}
	public StartupRecordData(StartupRecordDataId id, String jsonData) {
		this.id = id;
		this.jsonData = jsonData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ipcId", column = @Column(name = "ipc_id", nullable = false)),
			@AttributeOverride(name = "sampleId", column = @Column(name = "sample_id", nullable = false)),
			@AttributeOverride(name = "section", column = @Column(name = "section", nullable = false))})
	@NotNull
	public StartupRecordDataId getId() {
		return this.id;
	}

	public void setId(StartupRecordDataId id) {
		this.id = id;
	}

	@Column(name = "json_data")
	public String getJsonData() {
		return this.jsonData;
	}

	public void setJsonData(String jsonData) {
		this.jsonData = jsonData;
	}

}
