package user.inprocessChcks;
// Generated Jun 2, 2023, 2:52:26 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;

/**
 * StartupRecordDataId generated by hbm2java
 */
@Embeddable
public class StartupRecordDataId implements java.io.Serializable {

	private int ipcId;
	private int sampleId;
	private String section;

	public StartupRecordDataId() {
	}

	public StartupRecordDataId(int ipcId, int sampleId, String section) {
		this.ipcId = ipcId;
		this.sampleId = sampleId;
		this.section = section;
	}

	@Column(name = "ipc_id", nullable = false)
	public int getIpcId() {
		return this.ipcId;
	}

	public void setIpcId(int ipcId) {
		this.ipcId = ipcId;
	}

	@Column(name = "sample_id", nullable = false)
	public int getSampleId() {
		return this.sampleId;
	}

	public void setSampleId(int sampleId) {
		this.sampleId = sampleId;
	}

	@Column(name = "section", nullable = false)
	@NotNull
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StartupRecordDataId))
			return false;
		StartupRecordDataId castOther = (StartupRecordDataId) other;

		return (this.getIpcId() == castOther.getIpcId())
				&& (this.getSampleId() == castOther.getSampleId())
				&& ((this.getSection() == castOther.getSection()) || (this
						.getSection() != null
						&& castOther.getSection() != null && this.getSection()
						.equals(castOther.getSection())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIpcId();
		result = 37 * result + this.getSampleId();
		result = 37 * result
				+ (getSection() == null ? 0 : this.getSection().hashCode());
		return result;
	}

}
